export const LBANK_FUTURES_URL = "https://www.lbank.com/futures/debtusdt";

export const lbankSelectors = {
    // Presence means user IS logged in (opposite to MEXC logic)
    loginIndicator: "html body div#__next section.sc-jgyNOb.jTLWIE.lbk-trading-layout.lbk-trading-layout-professional-right.adjustable.ru header.sc-eZceyY.dUA-dID.lbank-header div.sc-MAqyW.grtnhR div.sc-cbfGDZ.guSjua.header-right div.sc-bTtZEv.jvZgKX.sc-fYyKnq.gygAhZ span.sc-hQIyOC.cSvkLn a.sc-fSKiAx.jVCpYC.a-link img.sc-bkldj.grEAWS",

    // Token quantity input field inside order form
    tokenQuantityInput: "html body div#__next section.sc-jgyNOb.jTLWIE.lbk-trading-layout.lbk-trading-layout-professional-right.adjustable.ru main.sc-bJjNXm.eWvQZs.lbk-trading-layout-main.horizontal section.sc-gcxUDs.bdlywA.trading_block.vertical section.sc-gcxUDs.bdlywA.trading_block.vertical div.sc-fWQKxP.bOKXsY.lbank-tabs.lbank-tabs-top.sc-kmtlux.fkbggY.orderboard_tabs.futures_orderboard_tabs div.sc-caPbAK.ctJcbQ.lbank-tabs-tabpane-content-holder div.lbank-tabs-tabpane-content.lbank-tabs-tabpane-content-top div.lbank-tabs-tabpane.lbank-tabs-tabpane-active div.sc-hEBzJi.giGBGG.futures_orderboard div.futures_orderboard_content div.futures_orderboard_forms div.sc-dOGYXd.cinBsS.orderboard_form div.sc-bnfANK.iDdiMQ.mini_form_item.sc-eTZVu.cnMLga.amount_form_item.val_len_0 div.sc-cCjUiG.knpFjn.sc-cOxWqc.gpBAMC.mini_form_input.lbank-input-number.lbank-input.lbank-input-large.lbank-input-outlined input.sc-hhOBVt.jHZCup.lbank-input-core.lbank-input-has-affter",

    // Toggle Open tab
    openToggleButton: "html body div#__next section.sc-jgyNOb.jTLWIE.lbk-trading-layout.lbk-trading-layout-professional-right.adjustable.ru main.sc-bJjNXm.eWvQZs.lbk-trading-layout-main.horizontal section.sc-gcxUDs.bdlywA.trading_block.vertical section.sc-gcxUDs.bdlywA.trading_block.vertical div.sc-fWQKxP.bOKXsY.lbank-tabs.lbank-tabs-top.sc-kmtlux.fkbggY.orderboard_tabs.futures_orderboard_tabs div.sc-caPbAK.ctJcbQ.lbank-tabs-tabpane-content-holder div.lbank-tabs-tabpane-content.lbank-tabs-tabpane-content-top div.lbank-tabs-tabpane.lbank-tabs-tabpane-active div.sc-hEBzJi.giGBGG.futures_orderboard div.index_lbk-row__VKjuM.index_lbk-toggle__tphea.sc-fIXfXT.jYMNkb.open_close_toggle button.index_lbk-toggle-button__v6Loz.open_close_btn.index_selected__KFvWG.open_close_btn_selected",

    // Action buttons
    openLongButton: "html body div#__next section.sc-jgyNOb.jTLWIE.lbk-trading-layout.lbk-trading-layout-professional-right.adjustable.ru main.sc-bJjNXm.eWvQZs.lbk-trading-layout-main.horizontal section.sc-gcxUDs.bdlywA.trading_block.vertical section.sc-gcxUDs.bdlywA.trading_block.vertical div.sc-fWQKxP.bOKXsY.lbank-tabs.lbank-tabs-top.sc-kmtlux.fkbggY.orderboard_tabs.futures_orderboard_tabs div.sc-caPbAK.ctJcbQ.lbank-tabs-tabpane-content-holder div.lbank-tabs-tabpane-content.lbank-tabs-tabpane-content-top div.lbank-tabs-tabpane.lbank-tabs-tabpane-active div.sc-hEBzJi.giGBGG.futures_orderboard div.futures_orderboard_content div.sc-iMGJAB.gzEegW.orderboard_buttons div.sc-hhoQlF.gCpNIE.orderboard_flexible_values.one_line.buttons div.info div.btnOpen span.text",
    openShortButton: "html body div#__next section.sc-jgyNOb.jTLWIE.lbk-trading-layout.lbk-trading-layout-professional-right.adjustable.ru main.sc-bJjNXm.eWvQZs.lbk-trading-layout-main.horizontal section.sc-gcxUDs.bdlywA.trading_block.vertical section.sc-gcxUDs.bdlywA.trading_block.vertical div.sc-fWQKxP.bOKXsY.lbank-tabs.lbank-tabs-top.sc-kmtlux.fkbggY.orderboard_tabs.futures_orderboard_tabs div.sc-caPbAK.ctJcbQ.lbank-tabs-tabpane-content-holder div.lbank-tabs-tabpane-content.lbank-tabs-tabpane-content-top div.lbank-tabs-tabpane.lbank-tabs-tabpane-active div.sc-hEBzJi.giGBGG.futures_orderboard div.futures_orderboard_content div.sc-iMGJAB.gzEegW.orderboard_buttons div.sc-hhoQlF.gCpNIE.orderboard_flexible_values.one_line.buttons div.info div.btnClose span.text",

    closeToggleButton: "html body div#__next section.sc-jgyNOb.jTLWIE.lbk-trading-layout.lbk-trading-layout-professional-right.adjustable.ru main.sc-bJjNXm.eWvQZs.lbk-trading-layout-main.horizontal section.sc-gcxUDs.bdlywA.trading_block.vertical section.sc-gcxUDs.bdlywA.trading_block.vertical div.sc-fWQKxP.bOKXsY.lbank-tabs.lbank-tabs-top.sc-kmtlux.fkbggY.orderboard_tabs.futures_orderboard_tabs div.sc-caPbAK.ctJcbQ.lbank-tabs-tabpane-content-holder div.lbank-tabs-tabpane-content.lbank-tabs-tabpane-content-top div.lbank-tabs-tabpane.lbank-tabs-tabpane-active div.sc-hEBzJi.giGBGG.futures_orderboard div.sc-iMGJAB.gzEegW.orderboard_buttons div.sc-hhoQlF.gCpNIE.orderboard_flexible_values.one_line.buttons div.info div.btnClose span.text",
    closeShortButton: "html body div#__next section.sc-jgyNOb.jTLWIE.lbk-trading-layout.lbk-trading-layout-professional-right.adjustable.ru main.sc-bJjNXm.eWvQZs.lbk-trading-layout-main.horizontal section.sc-gcxUDs.bdlywA.trading_block.vertical section.sc-gcxUDs.bdlywA.trading_block.vertical div.sc-fWQKxP.bOKXsY.lbank-tabs.lbank-tabs-top.sc-kmtlux.fkbggY.orderboard_tabs.futures_orderboard_tabs div.sc-caPbAK.ctJcbQ.lbank-tabs-tabpane-content-holder div.lbank-tabs-tabpane-content.lbank-tabs-tabpane-content-top div.lbank-tabs-tabpane.lbank-tabs-tabpane-active div.sc-hEBzJi.giGBGG.futures_orderboard div.futures_orderboard_content div.sc-iMGJAB.gzEegW.orderboard_buttons div.sc-hhoQlF.gCpNIE.orderboard_flexible_values.one_line.buttons div.info div.btnClose span.text",
    closeLongButton: "html body div#__next section.sc-jgyNOb.jTLWIE.lbk-trading-layout.lbk-trading-layout-professional-right.adjustable.ru main.sc-bJjNXm.eWvQZs.lbk-trading-layout-main.horizontal section.sc-gcxUDs.bdlywA.trading_block.vertical section.sc-gcxUDs.bdlywA.trading_block.vertical div.sc-fWQKxP.bOKXsY.lbank-tabs.lbank-tabs-top.sc-kmtlux.fkbggY.orderboard_tabs.futures_orderboard_tabs div.sc-caPbAK.ctJcbQ.lbank-tabs-tabpane-content-holder div.lbank-tabs-tabpane-content.lbank-tabs-tabpane-content-top div.lbank-tabs-tabpane.lbank-tabs-tabpane-active div.sc-hEBzJi.giGBGG.futures_orderboard div.futures_orderboard_content div.sc-iMGJAB.gzEegW.orderboard_buttons div.sc-hhoQlF.gCpNIE.orderboard_flexible_values.one_line.buttons div.info div.btnOpen span.text"
};